# fly.toml app configuration file for your Telegram bot on Fly.io

app = 'python-exam-mi-pug'
primary_region = 'otp'

[build]

[http_service]
  internal_port = 8080          
  auto_stop_machines = false    
  auto_start_machines = true   
  min_machines_running = 1   
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024

