# fly.toml app configuration file for your Telegram bot on Fly.io

app = 'python-exam-mi-pug'
primary_region = 'otp'

[build]

[http_service]
  internal_port = 8080          # Port your app listens on
  force_https = true            # Enforces HTTPS
  auto_stop_machines = false    # Prevent Fly from auto-stopping your app
  auto_start_machines = true    # Let Fly auto-start the app when needed
  min_machines_running = 1      # Ensure one machine is always running
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024

